### ISSUE TITLE
Add another credit card provider color theme

### ISSUE THREAD

**Issue by riandy-dimas** [riandy-dimas/credit-card-form#1]
Currently, these are the cards provider that already provided:
- [x] Visa
- [x] Discover
- [x] Mastercard
- [x] American Express

To determine the suitable credit card, we used [payment Library](https://www.npmjs.com/package/payment). So you will be able to add the following credit card:
- [x] JCB -- @wahyuoi
- [x] Diners Club -- @funwaa 
- [ ] Maestro
- [ ] Laser
- [x] UnionPay -- @Ryukishi 
- [x] Elo -- @Ryukishi 
- [x] Hipercard -- @Ryukishi 

P.S see [this reference](https://www.npmjs.com/package/payment#paymentfnscardtypenumber) to see the credit card type provider.

Please add another credit card provider by making sure to change/update:
1. `utils.js` in the following function:
```
function getCardColorByType(cardType = "other") {
  const cards = getCardTypeList();
  let color = "#484848";
  switch (cardType) {
    case cards.visa:
      color = "rgb(0, 87, 159)";
      break;
    case cards.mastercard:
      color = "rgb(248, 159, 21)";
      break;
    case cards.discover:
      color = "rgb(188, 44, 27)";
      break;
    case cards.amex:
      color = "rgb(0, 112, 209)";
      break;
    default:
      break;
  }
  return color;
}
```
2. Update `card/styles.scss` so your card styling/color matched with the one you stated in the `utils.js`
3. Do not forget to add the credit card logo in `assets` folder

**Comment by wahyuoi** [comment]
Hey @riandy-dimas, may I handle this issue?

**Comment by riandy-dimas** [comment]
Sure, go ahead @wahyuoi 👍

**Comment by Beat-tech** [comment]
Hello! I have added the maestro credit card color theme. This is my first time at Hacktober and also doing a pull request... still haven't managed to complete it but I am trying! :)

**Comment by riandy-dimas** [comment]
Hi @Beat-tech ! thank you for participating, can't wait for your PR soon! 😁

**Comment by Beat-tech** [comment]
Thank you @riandy-dimas !! I think I did it :)

**Comment by funwaa** [comment]
Added diners club in #7 
I also think the JCB logo should be PNG with transparent background :)

**Comment by riandy-dimas** [comment]
> Added diners club in #7
> I also think the JCB logo should be PNG with transparent background :)

Ah I missed that part, thanks @funwaa ! 
Do you mind to update the JCB logo to become a transparent one @wahyuoi ? I will take it if you won't.

**Comment by wahyuoi** [comment]
sure @riandy-dimas

**Comment by Ryukishi** [comment]
Hey @riandy-dimas I'd like to add the Hipercard

**Comment by Ryukishi** [comment]
I also added the unionpay one. Both PR's are open for review!

**Comment by Ryukishi** [comment]
Hey @riandy-dimas I read in this Wikipedia article: https://en.wikipedia.org/wiki/Laser_(debit_card) that Laser debit cards were withdrawn from the market in 2014. I was already wondering what the deal was because I could not find their website. Are you sure you still want to add it to the project?

**Comment by riandy-dimas** [comment]
Wow, I just figured it out that Laser Card has been withdrawn from the market, thanks for your information @Ryukishi. Since this app is just intended for detecting credit card providers so I think it is still fine to includes it.
