### ISSUE TITLE
Add responsive styling and some improvements

### ISSUE THREAD

**Issue by lemokami** [riandy-dimas/credit-card-form#12]
I will help in making the mobile view as well as some style changes to make the website better. I would need @riandy-dimas permission to do this. I will submit the PR this month as part of Hactoberfest

**Comment by riandy-dimas** [comment]
What do you plan for the improvement @Jesswinw ? Glad for me to receive your help 😄

**Comment by lemokami** [comment]
some style changes of the interface as well as the form
