### ISSUE TITLE
Move assets from codesandbox to this repo

### ISSUE THREAD

**Issue by wahyuoi** [riandy-dimas/credit-card-form#14]
There are 4 card logos that using assets from codesandbox, I feel it will be better to maintain own assets

```
cat src/card/styles.scss | grep codesandbox
      background-image: url("https://uploads.codesandbox.io/uploads/user/05ecbb71-49a1-4af7-bf06-27c4046fa1c5/ZsDH-Visa_Inc._logo.svg.png");
      background-image: url("https://uploads.codesandbox.io/uploads/user/05ecbb71-49a1-4af7-bf06-27c4046fa1c5/RDaJ-128px-Mastercard-logo.svg.png");
      background-image: url("https://uploads.codesandbox.io/uploads/user/05ecbb71-49a1-4af7-bf06-27c4046fa1c5/e8s_-127px-Discover_Card_logo.svg.png");
      background-image: url("https://uploads.codesandbox.io/uploads/user/05ecbb71-49a1-4af7-bf06-27c4046fa1c5/VF8c-american-express-6-675747.png");

```

feel free to grab this issue and send a pr :D

**Comment by wolffshots** [comment]
I'm going to give this a go, can I get assigned it please?

**Comment by Mehrapi** [comment]
I have createda pull request for this issue "Created assets/cardLogos for the logos and updated the css #15".

**Comment by Mehrapi** [comment]
> I'm going to give this a go, can I get assigned it please?

I didn' t see this message. I'm sorry.

**Comment by jadonwolffs** [comment]
> > I'm going to give this a go, can I get assigned it please?
> 
> I didn' t see this message. I'm sorry.

no worries, I'll wait for the contributor to see what we can do
