### ISSUE TITLE
Remove unnecessary scroll while keeping full width & height viewport

### ISSUE THREAD

**Issue by riandy-dimas** [riandy-dimas/credit-card-form#2]
If you run the app you will find that the page can be scrolled both vertically and horizontally. Please remove them as those are unnecessary. Nevertheless, make sure that the app still filling up the page with full width and height.

**Comment by abhishekjain35** [comment]
I would like to fix it. If you could assign it to me. @riandy-dimas

**Comment by riandy-dimas** [comment]
Sure go ahead @abhishekjain35 👍

**Comment by Trupti-Bhandari** [comment]
I would like to work on this.Can you assign me this @riandy-dimas ?

**Comment by riandy-dimas** [comment]
Hi @Trupti-Bhandari , there is already someone who assigned by this issue, let us wait for him first ya. Thanks!

**Comment by Trupti-Bhandari** [comment]
Okay @riandy-dimas

**Comment by abhishekjain35** [comment]
Ok, working on it.

**Comment by abhishekjain35** [comment]
I've fixed it and created PR #4. Please review it. @riandy-dimas @Trupti-Bhandari

**Comment by riandy-dimas** [comment]
Great job @abhishekjain35 thank you for your contribution!
